# Generated by Django 5.1.2 on 2024-10-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shortener',
            new_name='ShortenedURL',
        ),
    ]
